Controllers/ArchivosController.cs
using Microsoft.AspNetCore.Mvc;
using SubirArchivos.Models;
using System.Globalization;

namespace SubirArchivos.Controllers
{
    public class ArchivosController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        List<ArchivoModel> archivos = new List<ArchivoModel>();
        ListFilesModel files = new ListFilesModel();

        public ArchivosController(IWebHostEnvironment webHost)
        {
            _webHostEnvironment = webHost;
        }


        public IActionResult Index()
        {
            return View();

        }

        [HttpPost]
        public IActionResult Upload(ArchivoModel archivo)
        {
            try
            {
                string fileName = archivo.File.FileName;


                if (fileName.Length == 0)
                {
                    return BadRequest();
                }
                else
                {
                    //var path = Path.Combine(_webHostEnvironment.ContentRootPath, "Files");
                    var path = Path.Combine(@"C:/", "Files");

                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    string fullPath = Path.Combine(path, fileName); 

                    using (var stream = new FileStream(fullPath, FileMode.Create))
                    {
                        archivo.File.CopyTo(stream);
                    }

                        files.Archivos = new List<ArchivoModel> { new ArchivoModel { Name = fileName, Fecha = archivo.Fecha, File = archivo.File } }; 

                    return View("Index", files.ObternerArchivos());
                }
            }
            catch (Exception)
            {

                throw;
            }
        }



    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SubirArchivos.Models;
using System.Diagnostics;

namespace SubirArchivos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Archivos/Index.cshtml
@model List<ArchivoModel>;
@{
    ViewData["Title"] = "Index";
}
<h1>Subir archivos</h1>
<div class="container w-50">

    <div class="form-control">
        <form method="post" asp-controller="Archivos" asp-action="Upload" enctype="multipart/form-data">
            <div class="row">
                <div class="col">
                    <label class="form-label">Escriba el nombre: </label>
                    <input type="text" name="Name" id="ejemplo" class="form-control mb-3" />
                    <label class="form-label" >Seleccione el archivo</label>
                    <input type="file" multiple name="File" id="ejemplo" class="form-control mb-3" />
                    <label class="form-label">Seleccione la Fecha</label>
                    <input type="date" name="Fecha" class="form-control mb-4" />
                </div>
                <button type="submit" class="btn btn-primary btn-md">Save</button>
            </div>
        </form>
    </div>

</div>

@* @using (Html.BeginForm("Upload", "Archivos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="File" id="fileName" />
    <button type="submit" class="btn btn-primary">Save</button>
} *@


<div class="container mt-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Name</td>
                <td>Fecha</td>
                <td>Archivo</td>
            </tr>



        </thead>
        <tbody>
            @if(Model != null)
            {
                @foreach (var file in Model)
                {
                    <tr>
                        <td>@file.Name</td>
                        <td>@file.Fecha</td>
                        <td>@file.File</td>

                    </tr>
                }
            }

        </tbody>
    </table>
</div>


Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SubirArchivos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SubirArchivos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SubirArchivos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Archivos" asp-action="Index">Subir Archivos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SubirArchivos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>